### 포인트 정책 생성
POST {{host}}/points/policies
X-Admin-Id: A120115
Content-Type: application/json

{
  "code": "REVIEW_EARN",
  "name": "리뷰 적립",
  "description": "리뷰 작성 시 포인트 적립",
  "platformId": "order",
  "expirationCondition": {
    "type": "DURATION",
    "days": 365,
    "hours": null,
    "end": null
  }
}
