### 포인트 사용 복구
POST {{host}}/points/transactions/restore
X-Admin-Id: A120115
Content-Type: application/json

{
  "relatedTransactionId": "{{pointUseTransactionId}}",
  "orderId": "ORD-2",
  "idempotencyKey": "restore:{{pointUseTransactionId}}"
}
