spring:
  application:
    name: benefit-consumer
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: mongodb://localhost:27017/benefit
  data:
    redis:
      url: redis://localhost:6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: benefit-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
