@policyId = replace-policy-id

### 유저 쿠폰 발급 가능 여부 확인
POST {{host}}/coupons/wallets/issue/check
X-User-Id: U120115
Content-Type: application/json

{
  "policyId": "{{policyId}}",
  "segmentMatched": true
}
