spring:
  application:
    name: benefit-api
  config:
    import: optional:classpath:application.yml
  jackson:
    visibility:
      field: any
  threads:
    virtual:
      enabled: true
server:
  port: 8080
